import ast
import os
import sys
import importlib
import inspect
import re
import libcst as cst
import argparse


root = ""

# this was generated by chatGPT and manually edited/cleaned up
# if the annotation looks tricky or unclear, it's commented out
type_map = {
    'A dictionary with keys representing nodes and values representing': 'dict[Incomplete, Incomplete]',
    'list of floats of length m': 'list[float]',
    'float, optional': 'float',
    'object (default=None)': None,
    'function, optional': 'Callable[..., Incomplete]',
    'NetworkX simple graph': 'Graph[Incomplete]',
    'dict or None': 'dict[Incomplete, Incomplete]',
    'float between (0, 1), optional (default=0.01)': 'float',
    'SciPy sparse array': 'sparray',
    'List': 'list[Incomplete]',
    'A new graph.': 'Graph[Incomplete]',
    ':class:`set`': 'set[Incomplete]',
    'hashable object': None,
    'integer in [1000, 10000]': 'int',
    'string or None, optional (default: None)': 'str',
    'int,': 'int',
    'iterable of node pairs, optional (default = None)': 'Iterable[Incomplete]',
    'object': None,
    'string': 'str',
    'set': 'set[Incomplete]',
    '__getattr__, __dir__, __all__': None,
    'list or generator': 'list[Incomplete]',
    'The full join graph with the same type as G.': 'Graph[Incomplete]',
    'instance of `sympy.core.add.Add`': None,
    'dict, optional': 'dict[Incomplete, Incomplete]',
    'node': None,
    '(nx.PlanarEmbedding, list) tuple': 'tuple[PlanarEmbedding[Incomplete], list[Incomplete]]',
    'int | None': 'int',
    "string or None, optional (default='weight')": 'str',
    'Boolean': 'bool',
    'A dict keyed by edge 2-tuple to the number of shortest paths': 'dict[tuple[Incomplete, Incomplete], int]',
    'integer, float': 'int | float',
    'A new graph with the same type as G.': 'Graph[Incomplete]',
    'value | list': 'Incomplete | list[Incomplete]',
    'NetworkX graph constructor, optional (default=nx.Graph)': 'Graph[Incomplete]',
    'directed graph': 'Graph[Incomplete]',
    'Python type (default: str)': 'type[Incomplete]',
    'networkx graph': 'Graph[Incomplete]',
    'NetworkX MultiGraph or MultiDiGraph.': 'MultiDiGraph[Incomplete]',
    'iterable, required': 'Iterable[Incomplete]',
    'Python type (default: None)': 'type[Incomplete]',
    'list or iterable': 'list[Incomplete]',
    'Graph or None (default)': 'Graph[Incomplete]',
    'file-like object': None,
    'iterable of pairs of nodes, optional (default: all pairs)': 'Iterable[Incomplete]',
    'list, iterable': 'list[Incomplete]',
    'int, float, str, Python type, optional': None,
    'A new graph with the same type as the first graph in list': 'Graph[Incomplete]',
    'integer or float': 'int | float',
    'G: NetworkX Graph': 'Graph[Incomplete]',
    'object comparable with existing values.': None,
    'G: Graph object': 'Graph[Incomplete]',
    'iterable container': 'Iterable[Incomplete]',
    'callable, optional': 'Callable[..., Incomplete]',
    'networkx Graph': 'Graph[Incomplete]',
    'number of colors to use': 'int',
    'dict key (optional)': 'dict[Incomplete, Incomplete]',
    'a sequence of intervals, say (l, r) where l is the left end,': 'Iterable[Incomplete]',
    'Graph constructor (optional, default = nx.Graph)': 'Graph[Incomplete]',
    'nx.PlanarEmbedding': 'PlanarEmbedding[Incomplete]',
    'v: object': None,
    '(float, float)': 'tuple[float, float]',
    'nx.Graph': 'Graph[Incomplete]',
    'list of integers': 'list[int]',
    'NetworkX DiGraph': 'DiGraph[Incomplete]',
    'node, iterable of nodes, or None (default=None)': None,
    'object.': None,
    'networkx.Graph': 'Graph[Incomplete]',
    'scipy.sparse array': 'sparray',
    'iterator': 'Iterator[Incomplete]',
    'dict or a set of 2 or 3 tuples': 'dict[Incomplete, Incomplete] | set[tuple[Incomplete, ...]]',
    'function, or dict or list of lists, tuples or sets': 'dict[Incomplete, Incomplete]',
    'string or file or callable or None': 'Callable[..., Incomplete]',
    'G: Networkx Graph': 'Graph[Incomplete]',
    "string (default: 'weight')": 'str',
    '(graph, set)': 'tuple[Graph[Incomplete], set[Incomplete]]',
    "str in {'bsr', 'csr', 'csc', 'coo', 'lil', 'dia', 'dok'}": 'str',
    'list of ints': 'list[int]',
    'str': 'str',
    'int': 'int',
    'file or string': 'str',
    'A random graph containing no path on four vertices.': 'Graph[Incomplete]',
    'list': 'list[Incomplete]',
    'collection of nodes (default=G.nodes)': None,
    'dictionary of dictionaries': 'dict[Incomplete, Incomplete]',
    'Graph or list of Graphs': 'Graph[Incomplete]',
    'node, optional (default: first node in list(G))': None,
    'list or container of two-tuples': 'list[Incomplete]',
    'float between (0, 1), optional (default=0.1)': 'float',
    'Boolean function with two arguments': 'Callable[..., Incomplete]',
    'nx.DiGraph | nx.Graph': 'DiGraph[Incomplete]',
    'Counter, or dictionary of Counters': 'Counter[Incomplete] | dict[Incomplete, Counter[Incomplete]]',
    'Sequence[Number]': 'Sequence[float]',
    'graph: NetworkX graph': 'Graph[Incomplete]',
    'string, optional (default=None)': 'str',
    'NetworkX graph': 'Graph[Incomplete]',
    'function (optional)': 'Callable[..., Incomplete]',
    '(multi)digraph-like': 'DiGraph[Incomplete]',
    'iterable or iterator of pairs of nodes, optional (default: None)': 'Iterator[Incomplete]',
    'sequence': 'Iterable[Incomplete]',
    'int, an odd prime number.': 'int',
    'key, optional': None,
    'Python type, optional': 'type[Incomplete]',
    'SubGraph View': 'Graph[Incomplete]',
    'str or None, optional (default: None)': 'str',
    'number': 'float',
    'bool (default: True)': 'bool',
    'bool (default: False)': 'bool',
    'directed edges': None,
    'Networkx graph': 'Graph[Incomplete]',
    'list or iterable of set of nodes': 'set[Incomplete]',
    'four-tuple of numbers, optional': 'tuple[float, float, float, float]',
    'string, optional (default="weight")': 'str',
    'list of floats or float': 'list[float] | float',
    'NetworkX multigraph': 'MultiGraph[Incomplete]',
    'set | node': 'set[Incomplete] | Incomplete',
    'NetworkX Graph': 'Graph[Incomplete]',
    'graph': 'Graph[Incomplete]',
    'dictionary': 'dict[Incomplete, Incomplete]',
    'float': 'float',
    'a graph with the same type as the first graph in list': 'Graph[Incomplete]',
    ':class:`networkx.Graph`': 'Graph[Incomplete]',
    'NetworkX `Graph`': 'Graph[Incomplete]',
    'Graph Instance, Constructor or None': 'Graph[Incomplete]',
    'iterable': 'Iterable[Incomplete]',
    '(bool, NetworkX graph) tuple': 'tuple[bool, Graph[Incomplete]]',
    'weight: int or float': 'int | float',
    "str in {'dense', 'bsr', 'csr', 'csc', 'coo', 'lil', 'dia', 'dok'}": 'str',
    'A union graph with the same type as G.': 'Graph[Incomplete]',
    'numpy.array (optional, default=None)': 'np.ndarray[Incomplete, Incomplete]',
    'string | list': 'str | list[Incomplete]',
    '`abc.collections.Iterable` instance': 'Iterable[Incomplete]',
    'NetworkX graph constructor, optional (default MultiDiGraph)': 'MultiDiGraph[Incomplete]',
    'list or None, optional (default=None)': 'list[Incomplete]',
    'MultiDiGraph instance, optional': 'MultiDiGraph[Incomplete]',
    'set of 2 or 3 tuples.': 'set[tuple[Incomplete, ...]]',
    'node in `G`': None,
    'positive integer': 'int',
    'list, optional': 'list[Incomplete]',
    'integer, random_state, or None (default)': None,
    '"1-1" or "1-0" or function, optional (default="1-1")': 'Callable[..., Incomplete]',
    'list of three-tuples': 'list[tuple[Incomplete, Incomplete, Incomplete]]',
    'Python type (default: int)': 'type[Incomplete]',
    'list of all nodes or "greedy"': 'list[Incomplete]',
    'string or int': 'str | int',
    'int or iterable container of nodes': 'int | Iterable[Incomplete]',
    'a prime number': 'int',
    'string or iterable': 'str',
    'networkx.Graph: summary graph': 'Graph[Incomplete]',
    'string (default: None)': 'str',
    'G: NetworkX graph': 'Graph[Incomplete]',
    'A graph with the same type as the first graph in list': 'Graph[Incomplete]',
    'scalar': 'float',
    'NetworkX graph constructor, optional (default MultiGraph)': 'MultiGraph[Incomplete]',
    'string or int or sequence of strings or ints': 'str | int | Sequence[str | int]',
    'int, float, str, Python type, optional OBSOLETE': None,
    'bool (default False)': 'bool',
    'dict keyed by nodes': 'dict[Incomplete, Incomplete]',
    'numeric or timedelta': 'float',
    'list or container  optional(default is all nodes)': 'list[Incomplete]',
    'NetworkX graph or multigraph': 'MultiGraph[Incomplete]',
    'scalar, optional (default: the G edgedatadict for each edge)': 'float',
    'Graph/Multigraph or list of Graphs/MultiGraphs': 'MultiGraph[Incomplete]',
    'a generator of k-edge-subgraphs': 'Generator[Incomplete, Incomplete, Incomplete]',
    'string or file': 'str',
    'list or set or list of lists or list of sets': 'set[Incomplete]',
    'Parameter defined for participation of Common Neighbor': None,
    'graph :': 'Graph[Incomplete]',
    'bool or list of (label,type) tuples': 'bool | list[tuple[Incomplete, type[Incomplete]]]',
    'list or tuple of numbers or iterables of nodes': 'list[float] | tuple[float, ...] | Iterable[Incomplete]',
    'string, optional': 'str',
    'Bool or None, optional (default: False)': 'bool',
    'list of list of floats': 'list[list[float]]',
    'MultiDiGraph': 'MultiDiGraph[Incomplete]',
    'edge attribute key, optional (default=None)': None,
    'G: Networkx Graph object': 'Graph[Incomplete]',
    'list of nodes': 'list[Incomplete]',
    'callable | list': 'Callable[..., Incomplete] | list[Incomplete]',
    'tuple , default=(None, None)': 'tuple[Incomplete, Incomplete]',
    'int or NumPy RandomState or Generator instance, optional (default=None)': None,
    'iterable of paths': 'Iterable[Incomplete]',
    'list or iterator': 'list[Incomplete]',
    'm: numpy array': 'np.ndarray[Incomplete, Incomplete]',
    'The lowest common ancestor of node1 and node2,': None,
    'key': None,
    'iterable of sets of nodes': 'Iterable[Incomplete]',
    'bool': 'bool',
    'random state': None,
    'Graph container, optional,': 'Graph[Incomplete]',
    'dict': 'dict[Incomplete, Incomplete]',
    'float,': 'float',
    'tuple': 'tuple[Incomplete, ...]',
    'Graph': 'Graph[Incomplete]',
    'The object that results from ``next(iter(iterable))``': 'Iterable[Incomplete]',
    'NetworkX Graph of type create_using': 'Graph[Incomplete]',
    'function': 'Callable[..., Incomplete]',
    'DiGraph': 'DiGraph[Incomplete]',
    'bytes': 'bytes',
    'integer': 'int',
    'argmap.Signature': None,
    'a generator of k-edge-ccs. Each set of returned nodes': 'set[Incomplete]',
    'node or None (default: None)': None,
    'NumPy data-type, optional': 'np.dtype[Incomplete]',
    'list or iterator of strings': 'list[Incomplete]',
    '2-tuple': 'tuple[Incomplete, Incomplete]',
    'list or container': 'list[Incomplete]',
    'generator': 'Generator[Incomplete, Incomplete, Incomplete]',
    '2D numpy.ndarray': 'np.ndarray[Incomplete, Incomplete]',
    'NetworkX graph constructor, optional (default DiGraph)': 'DiGraph[Incomplete]',
    'a NetworkX graph instance': 'Graph[Incomplete]',
    '(set, set) tuple': 'tuple[set[Incomplete], set[Incomplete]]',
    'int or iterable': 'int | Iterable[Incomplete]',
    'list of nonnegative integers': 'list[int]',
    'NetworkX Graph or DiGraph': 'DiGraph[Incomplete]',
    'list of tuples (node_edit_path, edge_edit_path)': 'list[tuple[Incomplete, Incomplete]]',
    'callable': 'Callable[..., Incomplete]',
    'scipy sparse array': 'sparray',
    'string or function(G, colors)': 'Callable[..., Incomplete]',
    'NetworkX graph or two-tuple': 'Graph[Incomplete]',
    'i: object': None,
    'string or iterable of strings': 'str',
}


# This looks up the type annotation from type_map and removes any pandas-related qualifiers
# on the types
def filter_type_annotation(annotation: str) -> str | None:
    annotation = type_map.get(annotation)
    if annotation is None:
        return None
    parts = annotation.split()
    result = []
    for part in parts:
        if part.startswith("pandas.") or part.startswith("pd."):
            result.append(part.split(".")[-1])
        else:
            result.append(part)
    return " ".join(result)


types = set()


# This libCST applies a type annotation to a function parameter or return
class MethodAnnotator(cst.CSTTransformer):
    def __init__(self, func_or_method: str, param_name: str | None, annotation_str: str):
        self.param_name = param_name
        self.annotation = cst.Annotation(cst.parse_expression(annotation_str))
        if '.' in func_or_method:
            self.class_name, self.func_name = func_or_method.split('.')
        else:
            self.class_name = None
            self.func_name = func_or_method
        self.inside_target_class = self.class_name is None  # True for top-level functions

    def visit_ClassDef(self, node: cst.ClassDef):
        if self.class_name and node.name.value == self.class_name:
            self.inside_target_class = True

    def leave_ClassDef(self, original_node, node: cst.ClassDef):
        if self.class_name and node.name.value == self.class_name:
            self.inside_target_class = False
        return node

    def leave_FunctionDef(
        self, original_node: cst.FunctionDef, updated_node: cst.FunctionDef
    ) -> cst.FunctionDef:
        if not self.inside_target_class:
            return updated_node

        if original_node.name.value != self.func_name:
            return updated_node

        new_params = []
        for param in updated_node.params.params:
            if self.param_name and param.name.value == self.param_name and param.annotation is None:
                new_param = param.with_changes(annotation=self.annotation)
                new_params.append(new_param)
            else:
                new_params.append(param)
        if self.param_name is None:
            updated_node = updated_node.with_changes(returns=self.annotation)
        return updated_node.with_changes(
            params=updated_node.params.with_changes(params=new_params)
        )

# This function applies a type annotation to a parameter


def annotate_parameter(filename, function, parameter, annotation) -> None:
    with open(filename, "r") as f:
        code = f.read()
    module = cst.parse_module(code)
    transformer = MethodAnnotator(function, parameter, annotation)
    modified_module = module.visit(transformer)
    with open(filename, "w") as f:
        f.write(modified_module.code)


# This function applies a type annotation to a return
def annotate_return(filename, function, annotation) -> None:
    with open(filename, "r") as f:
        code = f.read()
    module = cst.parse_module(code)
    transformer = MethodAnnotator(function, None, annotation)
    modified_module = module.visit(transformer)
    with open(filename, "w") as f:
        f.write(modified_module.code)


# This function gets the type of a parameter from the docstring
# The extracted type might not be a legal type annotatation
def extract_param_type(docstring: str, param: str) -> str | None:
    if not docstring:
        return None
    lines = docstring.splitlines()
    try:
        start = lines.index("Parameters")
    except ValueError:
        return None
    # Look for "----------" after "Parameters"
    for i in range(start + 1, len(lines)):
        if re.match(r'^-+$', lines[i].strip()):
            param_start = i + 1
            break
    else:
        return None
    param_pattern = re.compile(rf'^{re.escape(param)}\s*:\s*(.+)$')
    for i in range(param_start, len(lines)):
        line = lines[i].strip()
        if not line:
            continue
        if re.match(r'^[A-Za-z_][A-Za-z0-9_]*\s*:', line):  # new param starts
            match = param_pattern.match(line)
            if match:
                matched = match.group(1).strip()
                return matched
        elif line.startswith(('See Also', 'Notes', 'Examples')):
            break  # past parameter section
    return None


# This function gets the type of a function return from the docstring
# The extracted type might not be a legal type annotatation
def extract_return_type(docstring: str) -> str | None:
    if not docstring:
        return None
    lines = docstring.splitlines()
    try:
        start = lines.index("Returns")
    except ValueError:
        return None
    # Look for "----------" after "Returns"
    for i in range(start + 1, len(lines)):
        if re.match(r'^-+$', lines[i].strip()):
            return_line = i + 1
            break
    else:
        return None
    # Extract the first non-empty, non-indented line after the dashed line
    for i in range(return_line, len(lines)):
        line = lines[i]
        if line.strip() == "":
            continue
        if not line.startswith(" "):  # likely the type line
            return line.strip()
        else:
            break  # We’ve passed the expected return type line
    return None


# This function gets the docstring for a particular function
def get_docstring(mod: str, func: str) -> str | None:
    try:
        module = importlib.import_module(mod)
        if '.' in func:
            cls_name, method_name = func.split('.', 1)
            cls = getattr(module, cls_name, None)
            if cls is None:
                return None
            obj = getattr(cls, method_name, None)
        else:
            obj = getattr(module, func, None)
        if obj is None:
            return None
        return inspect.getdoc(obj)
    except Exception as e:
        print(e)
        return None


def get_module_path(root: str, file_path: str) -> str:
    rel_path = os.path.relpath(file_path, root)
    no_ext = os.path.splitext(rel_path)[0]
    return no_ext.replace(os.path.sep, '.')


def process_function(module: str, class_name: str | None, func_node: ast.FunctionDef, pkg_name: str, show_types: bool) -> None:
    if func_node.name.startswith('__') and func_node.name.endswith('__'):
        return
    func_name = f"{class_name}.{func_node.name}" if class_name else func_node.name
    docstring = get_docstring(f"{pkg_name}.{module}", func_name)
    if docstring is None:
        return
    module_path = root + "/" + module.replace(".", "/") + ".pyi"
    global types
    for arg in func_node.args.args:
        if arg.arg in {'self', 'cls'}:
            continue
        if arg.annotation is None:
            arg_type = extract_param_type(docstring, arg.arg)
            if arg_type is None:
                continue
            types.add(arg_type)
            arg_type = filter_type_annotation(arg_type)
            if arg_type is None:
                continue
            if not show_types:
                annotate_parameter(module_path, func_name, arg.arg, arg_type)
    if func_node.returns is None:
        ret_type = extract_return_type(docstring)
        if ret_type is None:
            return
        if " : " in ret_type:
            ret_type = ret_type.split(" : ")[-1]
        types.add(ret_type)
        ret_type = filter_type_annotation(ret_type)
        if ret_type is None:
            return
        if not show_types:
            annotate_return(module_path, func_name, ret_type)


# Is this function decorated w/ @overload
def is_overload(func: ast.FunctionDef) -> bool:
    for decorator in func.decorator_list:
        if isinstance(decorator, ast.Name) and decorator.id == 'overload':
            return True
        if isinstance(decorator, ast.Attribute) and decorator.attr == 'overload':
            return True
    return False


def process_file(root: str, file_path: str, pkg_name: str, show_types: bool) -> None:
    module = get_module_path(root, file_path)
    with open(file_path, "r", encoding="utf-8") as f:
        try:
            tree = ast.parse(f.read(), filename=file_path)
        except SyntaxError:
            return
    for node in tree.body:
        if isinstance(node, ast.FunctionDef):
            if is_overload(node):
                continue
            process_function(module, None, node, pkg_name, show_types)
        elif isinstance(node, ast.ClassDef):
            for item in node.body:
                if isinstance(item, ast.FunctionDef):
                    if is_overload(item):
                        continue
                    process_function(module, node.name, item,
                                     pkg_name, show_types)


def walk_directory(root: str, pkg_name: str, show_types: bool) -> None:
    for dirpath, _, filenames in os.walk(root):
        for filename in filenames:
            if filename.endswith(".pyi"):
                process_file(root, os.path.join(
                    dirpath, filename), pkg_name, show_types)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("stubs", help="Stubs root directory")
    parser.add_argument("package", help="Runtime package")
    parser.add_argument("--show-types", action="store_true")
    args = parser.parse_args()
    root = args.stubs
    walk_directory(args.stubs, args.package, args.show_types)
    if args.show_types:
        for t in types:
            print(t)
